name: Release APK

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v0.0.1, v1.0, etc.

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true # Enable Flutter SDK caching

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Run Flutter Analyze
        run: flutter analyze

      - name: Run Unit Tests
        run: flutter test # Added test step for quality gate

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  create_release:
    runs-on: ubuntu-latest
    needs: build_and_test # This job depends on the build_and_test job
    permissions:
      contents: write # Required to create a GitHub release
    steps:
      - name: Download APK artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: app-release-apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true # Auto-generate release notes
          files: app-release.apk